services:
  db:
    image: mongo:5
    network_mode: host
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

volumes:
  mongo-data:
  mongo-config:
