services:
  app:
    image: konradpoweska/towel-monitoring
    build: .
    container_name: towel-monitoring
    ports:
      - 8080:80
    depends_on:
      - db
    restart: always
    environment:
      PORT: 80
      NODE_ENV: production
      MONGO_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db/
      MONGO_DB: towel-monitoring-prd
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_TRUST_HOST: true
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

  db:
    image: mongo:5
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

volumes:
  mongo-data:
  mongo-config:
