name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run checks
        run: npm run check
      - name: Run tests
        run: npm test
        env:
          MONGO_URL: mongodb://test:test@localhost/
          MONGO_DB: towel-tracking-test

    services:
      db:
        image: mongo:5
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: test
          MONGO_INITDB_DATABASE: towel-tracking-test
        ports:
          - 27017:27017
